Data_Preparation:
  test_size: 0.20
  random_state: 13

Train:
  Random_Forest:
    n_estimators: 127
    criterion: 'squared_error'
    max_depth: 28
    max_features: 1
    min_samples_split: 10
    min_samples_leaf: 2
    max_samples:  0.5969118095092534
    verbose: 1
    n_jobs: -1
  
  LightGBM:
    n_estimators: 96
    max_depth: 27
    learning_rate:  0.23713967967614558
    subsample: 0.9298857508586896
    min_child_weight: 13
    min_split_gain: 0.011156224241214138
    reg_lambda: 26.097675682171626
    n_jobs: -1